steps:
  - label: Build titus-agent-console debian package
    command: docker build --no-cache -t deb_nc release && docker run --rm -e TITUS_NETCONSOLE_VERSION=$(date +%Y%m%d).$(git rev-parse HEAD) -v $PWD:/src deb_nc:latest && mv *.deb titus-agent-netconsole.deb
    artifact_paths: "*.deb"
  - wait
  - trigger: titus-upload-debs
    async: false
    branches: "master"
    build:
      env:
        CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
        CALLER_UPLOAD_DEB: "titus-agent-netconsole.deb"
        CALLER_PACKAGE_NAME: "titus-agent-netconsole"
        BUILDKITE_CLEAN_CHECKOUT: "true"
